---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blockscout-l2-svc
  name: blockscout-l2-svc
spec:
  type: ClusterIP
  ports:
    - name: "blockscout-port"
      port: 4000
      targetPort: 4000
  selector:
    app: blockscout-l2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blockscout-l2
  name: blockscout-l2
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: blockscout-l2
  template:
    metadata:
      labels:
        app: blockscout-l2
    spec:
      containers:
        - image: blockscout/blockscout-optimism-bedrock-goerli
          imagePullPolicy: Always
          name: blockscout
          command:
            - 'bash'
            - '-c'
          args:
            - 'bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()" && bin/blockscout start'
          ports:
            - containerPort: 4000
              protocol: TCP
          env:
            - name: ETHEREUM_JSONRPC_VARIANT
              value: 'geth'
            - name: BLOCK_TRANSFORMER
              value: 'base'
            - name: ETHEREUM_JSONRPC_HTTP_URL
              value: 'http://l2-svc:9545'
            - name: ETHEREUM_JSONRPC_TRACE_URL
              value: 'http://l2-svc:9545'
            - name: DATABASE_URL
              value: 'postgresql://postgres:password@postgres-postgresql:5432/blockscout_l2?ssl=false'
            - name: SECRET_KEY_BASE
              value: '56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN'
            - name: ACCOUNT_REDIS_URL
              value: 'redis://redis-master:6379'
          envFrom:
          - configMapRef:
              name: blockscout-cm
        - image: ghcr.io/blockscout/visualizer:latest
          imagePullPolicy: Always
          name: visualizer
          ports:
            - containerPort: 8050
              protocol: TCP
          env:
            - name: VISUALIZER__SERVER__GRPC__ENABLED
              value: 'false'
        - image: ghcr.io/blockscout/smart-contract-verifier:latest
          imagePullPolicy: Always
          name: smart-contract-verifier
          ports:
            - containerPort: 8043
              protocol: TCP
          env:
            - name: VISUALIZER__SERVER__GRPC__ENABLED
              value: 'false'
      dnsPolicy: ClusterFirst
      restartPolicy: Always
