---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stateviz-svc
  name: stateviz-svc
spec:
  type: ClusterIP
  ports:
    - name: "stateviz-svc"
      port: 9090
      targetPort: 8080
  selector:
    app: stateviz
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: stateviz
  name: stateviz
spec:
  serviceName: stateviz-svc
  replicas: 1
  selector:
    matchLabels:
      app: stateviz
  template:
    metadata:
      labels:
        app: stateviz
    spec:
      containers:
        - args:
            - stateviz
            - -addr=0.0.0.0:8080
            - -snapshot=/op_log/snapshot.log
            - -refresh=10s
          image: ops-bedrock_stateviz
          imagePullPolicy: Never
          name: stateviz
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /op_log
              name: op-log
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: op-log
          persistentVolumeClaim:
            claimName: op-log-pvc
